services:
  php:
    build:
      context: ../
      dockerfile: docker/php-fpm/Dockerfile
    container_name: symfony6-php
    volumes:
      - ../app:/var/www/html

  nginx:
    image: nginx:stable-alpine
    container_name: symfony6-nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ../app:/var/www/html
      - ./php-fpm/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data: